In [1]:
import pandas as pd

In [2]:
df_site = pd.read_csv("base_midianet_site.csv")
df_radio = pd.read_csv("base_radio_conecta.csv")
df_tv = pd.read_csv("base_tv_panorama.csv")

# ANALISE ISOLADA SITE

In [3]:
df_site

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,70.887.041/3756-00,InvestMax Financeiro,PJ,Automotivo,6,2019,39546.39,Inativo
1,65.939.441/4825-00,KleanHome Produtos,PJ,Automotivo,5,2023,34983.41,Ativo
2,92.137.452/8220-65,Empório Sabores ME,PJ,Automotivo,1,2022,7411.42,Inativo
3,91.925.646/7866-78,QualiSaúde Clínicas,PJ,Automotivo,11,2021,31186.44,Inativo
4,88.827.020/9143-96,Haute Moda Ltda,PJ,Varejo,2,2023,14093.72,Ativo
...,...,...,...,...,...,...,...,...
125,371.079.541-99,Elisa Martins,PF,Varejo,11,2021,66578.14,Ativo
126,114.433.305-90,Ana Lima,PF,Tecnologia,9,2019,25724.62,Inativo
127,680.966.266-98,Bruno Souza,PF,Beleza,4,2018,26799.25,Ativo
128,498.954.683-00,Carlos Mendes,PF,Automotivo,4,2019,18449.76,Ativo
129,519.989.692-07,Diana Rocha,PF,Financeiro,9,2019,11133.04,Inativo

In [4]:
med_site = df_site['valor_ultima_campanha'].mean()
med_camp_site = df_site['qtd_campanhas'].mean()

In [5]:
# CLIENTES SITE COM MAIS CAMPANHAS DO QUE A MÉDIA
c_site_recorrente = df_site[df_site['qtd_campanhas'] > med_camp_site].sort_values(by='qtd_campanhas', ascending=False)
c_site_recorrente

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
56,54.778.849/8140-28,UniMed Saúde,PJ,Automotivo,12,2020,6197.78,Ativo
61,65.421.250/6106-40,ZoneMedia Tech,PJ,Construção,12,2023,16800.37,Ativo
8,07.652.103/5985-36,Yara Cosméticos Ltda,PJ,Automotivo,12,2024,28390.13,Ativo
9,77.138.861/7593-82,ZapFood Delivery,PJ,Construção,12,2018,9230.18,Ativo
124,255.131.478-07,Daniel Oliveira,PF,Moda,12,2020,43529.21,Inativo
...,...,...,...,...,...,...,...,...
37,74.390.352/9362-30,BetaCar Motors,PJ,Construção,7,2020,67861.86,Ativo
28,51.611.221/8899-91,UniLearn Educação,PJ,Automotivo,7,2024,65619.65,Ativo
14,56.334.722/6145-42,MegaVarejo S.A.,PJ,Automotivo,7,2019,42480.28,Ativo
25,66.505.901/2424-06,BetaCar Motors,PJ,Varejo,7,2018,75098.60,Ativo
31,241.592.066-54,Ana Lima,PF,Tecnologia,7,2021,16124.68,Ativo

In [6]:
c_site_valor_alto = df_site[df_site['valor_ultima_campanha'] > med_site].sort_values(by='valor_ultima_campanha', ascending=False)
c_site_valor_alto

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
102,81.667.872/6403-54,SoftEdge Sistemas,PJ,Turismo,1,2018,78180.32,Ativo
91,43.215.405/3647-80,Haute Moda Ltda,PJ,Varejo,3,2018,77640.40,Inativo
94,47.569.797/6597-01,Klara Beleza Ltda,PJ,Turismo,10,2019,77307.04,Ativo
59,65.816.255/4183-04,XtraVarejo Ltda,PJ,Varejo,3,2021,76674.28,Ativo
107,20.341.382/1773-00,XPrime Financeiro,PJ,Varejo,8,2020,76671.53,Inativo
...,...,...,...,...,...,...,...,...
77,66.356.039/4012-21,PecuáriaSul Agro,PJ,Construção,1,2024,42555.87,Ativo
14,56.334.722/6145-42,MegaVarejo S.A.,PJ,Automotivo,7,2019,42480.28,Ativo
82,30.743.885/8534-09,UltraFit Academia,PJ,Turismo,4,2021,41931.20,Inativo
73,48.411.361/1768-67,LivrariaCultura,PJ,Construção,10,2018,41143.32,Ativo
93,45.438.966/6946-41,JetTravel Turismo,PJ,Construção,2,2018,40759.93,Ativo

In [41]:
c_site_ouro = pd.merge(c_site_recorrente, c_site_valor_alto, how='inner')
c_site_ouro

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,255.131.478-07,Daniel Oliveira,PF,Moda,12,2020,43529.21,Inativo
1,25.425.824/3859-23,VidaPlena Saúde,PJ,Construção,12,2018,47943.46,Inativo
2,97.056.935/5722-73,UniLearn Educação,PJ,Automotivo,12,2023,60216.32,Ativo
3,62.328.706/8630-94,GastroTop Alimentos,PJ,Automotivo,12,2018,49574.36,Ativo
4,16.526.494/2164-36,InvestMax Financeiro,PJ,Automotivo,12,2024,64384.28,Ativo
5,51.692.555/2055-82,TurboAuto Motors,PJ,Construção,12,2020,57128.90,Ativo
6,18.697.946/0811-06,FrigoNorte Alimentos,PJ,Varejo,11,2022,52790.69,Ativo
7,99.193.064/9724-41,Centro Educacional Futuro,PJ,Turismo,11,2022,59154.12,Inativo
8,90.727.027/0307-57,ZapFood Delivery,PJ,Construção,11,2022,55563.30,Inativo
9,371.079.541-99,Elisa Martins,PF,Varejo,11,2021,66578.14,Ativo
10,32.770.619/0458-68,SoftEdge Sistemas,PJ,Turismo,11,2019,71018.26,Ativo
11,76.779.132/0382-89,FuturaTech Sistemas,PJ,Construção,10,2022,62812.68,Ativo
12,48.411.361/1768-67,LivrariaCultura,PJ,Construção,10,2018,41143.32,Ativo
13,33.110.605/0482-00,SuperNutri Alimentos,PJ,Turismo,10,2021,59166.40,Inativo
14,17.407.611/4589-21,CompreFácil Varejo,PJ,Automotivo,10,2019,57893.12,Ativo
15,40.708.537/7859-39,Galpão Construções,PJ,Turismo,10,2018,45823.99,Ativo
16,47.569.797/6597-01,Klara Beleza Ltda,PJ,Turismo,10,2019,77307.04,Ativo
17,70.041.364/8298-92,EduMax Cursos,PJ,Automotivo,10,2019,63412.19,Inativo
18,90.707.017/1292-92,Nativa Alimentos,PJ,Construção,9,2019,55868.97,Ativo
19,723.227.079-88,Yara Freitas,PF,Construção,9,2021,76061.97,Inativo
20,77.186.888/2036-60,BioFarma Saúde S.A.,PJ,Construção,9,2024,44803.21,Ativo
21,922.458.108-05,Camila Pereira,PF,Educação,9,2024,64628.73,Ativo
22,14.700.177/2543-95,LuzBrilho Beleza,PJ,Varejo,9,2024,44659.68,Ativo
23,02.864.782/8874-39,KidLearn Educação,PJ,Automotivo,9,2019,61443.24,Ativo
24,82.400.478/1470-00,GrupoFit Saúde,PJ,Turismo,9,2020,63379.61,Ativo
25,576.340.634-60,Igor Castro,PF,Turismo,9,2023,74650.75,Ativo
26,012.195.586-99,Helena Pinto,PF,Alimentação,8,2024,60542.02,Ativo
27,20.591.644/3354-70,OficinaTop Auto,PJ,Automotivo,8,2021,69952.78,Inativo
28,59.025.594/7326-60,OmniDigital Tech,PJ,Turismo,8,2018,43320.56,Inativo
29,27.646.796/5114-66,RedeTur Viagens,PJ,Construção,8,2023,61552.46,Ativo
30,20.341.382/1773-00,XPrime Financeiro,PJ,Varejo,8,2020,76671.53,Inativo
31,09.673.959/3563-40,BetaCar Motors,PJ,Varejo,8,2021,71496.80,Inativo
32,39.802.819/8230-07,AlphaVest Moda,PJ,Automotivo,7,2023,64045.37,Ativo
33,57.440.802/5303-68,InovaBuild Construtora,PJ,Automotivo,7,2023,75100.95,Ativo
34,50.986.824/4456-08,AlphaVest Moda,PJ,Turismo,7,2018,66138.54,Ativo
35,74.390.352/9362-30,BetaCar Motors,PJ,Construção,7,2020,67861.86,Ativo
36,51.611.221/8899-91,UniLearn Educação,PJ,Automotivo,7,2024,65619.65,Ativo
37,56.334.722/6145-42,MegaVarejo S.A.,PJ,Automotivo,7,2019,42480.28,Ativo
38,66.505.901/2424-06,BetaCar Motors,PJ,Varejo,7,2018,75098.60,Ativo

In [8]:
# CLIENTES OURO INATIVOS (FAZER PROPOSTA DE REATIVAÇÃO)
c_site_ouro[c_site_ouro['status'] == 'Inativo']

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,255.131.478-07,Daniel Oliveira,PF,Moda,12,2020,43529.21,Inativo
1,25.425.824/3859-23,VidaPlena Saúde,PJ,Construção,12,2018,47943.46,Inativo
7,99.193.064/9724-41,Centro Educacional Futuro,PJ,Turismo,11,2022,59154.12,Inativo
8,90.727.027/0307-57,ZapFood Delivery,PJ,Construção,11,2022,55563.30,Inativo
13,33.110.605/0482-00,SuperNutri Alimentos,PJ,Turismo,10,2021,59166.40,Inativo
17,70.041.364/8298-92,EduMax Cursos,PJ,Automotivo,10,2019,63412.19,Inativo
19,723.227.079-88,Yara Freitas,PF,Construção,9,2021,76061.97,Inativo
27,20.591.644/3354-70,OficinaTop Auto,PJ,Automotivo,8,2021,69952.78,Inativo
28,59.025.594/7326-60,OmniDigital Tech,PJ,Turismo,8,2018,43320.56,Inativo
30,20.341.382/1773-00,XPrime Financeiro,PJ,Varejo,8,2020,76671.53,Inativo
31,09.673.959/3563-40,BetaCar Motors,PJ,Varejo,8,2021,71496.80,Inativo

# ANALISE ISOLADA RADIO

In [9]:
df_radio

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,38.823.384/6878-38,Drive Motors Ltda,PJ,Varejo,11,2024,58366.41,Ativo
1,41.879.274/9176-52,FuturaTech Sistemas,PJ,Construção,1,2018,13548.70,Inativo
2,67.632.538/1591-13,MaisAgro Ltda,PJ,Turismo,7,2021,21065.88,Ativo
3,75.525.887/1161-98,XPrime Financeiro,PJ,Varejo,9,2018,58011.68,Inativo
4,36.852.702/5849-75,Klara Beleza Ltda,PJ,Turismo,4,2021,78174.99,Inativo
...,...,...,...,...,...,...,...,...
125,114.433.305-90,Ana Lima,PF,Tecnologia,12,2022,72800.52,Inativo
126,680.966.266-98,Bruno Souza,PF,Beleza,5,2021,52480.41,Inativo
127,498.954.683-00,Carlos Mendes,PF,Automotivo,1,2018,12562.69,Inativo
128,519.989.692-07,Diana Rocha,PF,Financeiro,3,2021,28700.25,Inativo
129,360.912.628-07,Eduardo Farias,PF,Saúde,11,2022,53500.05,Ativo

In [10]:
med_radio = df_radio['valor_ultima_campanha'].mean()
med_camp_radio = df_radio['qtd_campanhas'].mean()

In [11]:
c_radio_recorrente = df_radio[df_radio['qtd_campanhas'] > med_camp_radio].sort_values(by='qtd_campanhas', ascending=False)
c_radio_recorrente

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
125,114.433.305-90,Ana Lima,PF,Tecnologia,12,2022,72800.52,Inativo
8,79.803.432/5470-41,Centro Educacional Futuro,PJ,Turismo,12,2023,32623.34,Ativo
104,25.425.824/3859-23,VidaPlena Saúde,PJ,Construção,12,2021,56918.87,Inativo
61,12.147.922/3260-51,AgroPrime Ltda,PJ,Turismo,12,2018,72338.76,Ativo
53,33.110.605/0482-00,SuperNutri Alimentos,PJ,Turismo,12,2022,19085.21,Inativo
...,...,...,...,...,...,...,...,...
12,14.984.149/9290-50,GrupoFit Saúde,PJ,Automotivo,7,2019,24827.87,Inativo
56,04.955.549/6381-95,ViajarMais Turismo,PJ,Construção,7,2020,34272.72,Ativo
58,65.816.255/4183-04,XtraVarejo Ltda,PJ,Varejo,7,2019,53903.10,Ativo
2,67.632.538/1591-13,MaisAgro Ltda,PJ,Turismo,7,2021,21065.88,Ativo
63,18.310.985/3045-07,ClubFit Academia,PJ,Automotivo,7,2023,36498.28,Ativo

In [12]:
c_radio_valor = df_radio[df_radio['valor_ultima_campanha'] > med_radio].sort_values(by='valor_ultima_campanha', ascending=False)
c_radio_valor

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
85,99.193.064/9724-41,Centro Educacional Futuro,PJ,Turismo,8,2022,79298.02,Inativo
91,16.526.494/2164-36,InvestMax Financeiro,PJ,Automotivo,5,2021,79133.25,Ativo
4,36.852.702/5849-75,Klara Beleza Ltda,PJ,Turismo,4,2021,78174.99,Inativo
62,86.853.528/3643-25,BioNutri Saúde,PJ,Varejo,2,2020,77950.89,Ativo
90,43.215.405/3647-80,Haute Moda Ltda,PJ,Varejo,1,2018,77848.69,Inativo
...,...,...,...,...,...,...,...,...
22,81.599.418/5660-73,BioFarma Saúde S.A.,PJ,Construção,6,2022,44002.43,Ativo
36,74.390.352/9362-30,BetaCar Motors,PJ,Construção,5,2019,43097.41,Ativo
102,46.807.966/1469-39,TerraFirme Construtora,PJ,Varejo,2,2024,42295.14,Ativo
119,663.975.721-45,Zélio Araújo,PF,Agronegócio,7,2020,41970.49,Inativo
9,32.770.619/0458-68,SoftEdge Sistemas,PJ,Turismo,4,2024,41821.61,Ativo

In [42]:
c_radio_ouro = pd.merge(c_radio_recorrente, c_radio_valor, how='inner')
c_radio_ouro

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,114.433.305-90,Ana Lima,PF,Tecnologia,12,2022,72800.52,Inativo
1,25.425.824/3859-23,VidaPlena Saúde,PJ,Construção,12,2021,56918.87,Inativo
2,12.147.922/3260-51,AgroPrime Ltda,PJ,Turismo,12,2018,72338.76,Ativo
3,08.237.872/5268-90,JáCompra Varejo,PJ,Construção,12,2024,71503.40,Ativo
4,38.823.384/6878-38,Drive Motors Ltda,PJ,Varejo,11,2024,58366.41,Ativo
5,97.056.935/5722-73,UniLearn Educação,PJ,Automotivo,11,2022,68873.07,Ativo
6,06.241.520/5808-29,HighClass Moda,PJ,Construção,11,2022,64822.79,Inativo
7,360.912.628-07,Eduardo Farias,PF,Saúde,11,2022,53500.05,Ativo
8,56.334.722/6145-42,MegaVarejo S.A.,PJ,Automotivo,11,2018,52884.11,Ativo
9,09.894.808/5459-80,LavouraVerde Agro,PJ,Varejo,11,2018,67934.06,Inativo
10,21.753.377/2747-20,Atacadão Norte Ltda,PJ,Automotivo,11,2024,71106.13,Ativo
11,37.341.091/4455-05,WebFarm Agro,PJ,Turismo,10,2022,66316.00,Ativo
12,576.340.634-60,Igor Castro,PF,Turismo,9,2024,61207.54,Ativo
13,852.884.836-12,Eduardo Farias,PF,Saúde,9,2023,50568.14,Ativo
14,90.707.017/1292-92,Nativa Alimentos,PJ,Construção,9,2024,57943.57,Ativo
15,85.881.227/0915-16,Paço Automotivo Ltda,PJ,Varejo,9,2021,69897.63,Ativo
16,75.525.887/1161-98,XPrime Financeiro,PJ,Varejo,9,2018,58011.68,Inativo
17,15.587.722/2354-79,MercadoBom Varejo,PJ,Turismo,9,2018,72331.86,Ativo
18,67.187.738/2133-38,RuralBom Agro,PJ,Construção,9,2023,77594.33,Ativo
19,31.699.730/9461-30,WebStore Varejo,PJ,Turismo,9,2022,71709.92,Ativo
20,59.308.343/1078-01,QuantumSoft Tech,PJ,Automotivo,9,2018,70613.88,Ativo
21,61.250.988/3939-40,LuzBrilho Beleza,PJ,Construção,8,2023,49527.99,Ativo
22,95.831.835/5403-90,QualiSaúde Clínicas,PJ,Automotivo,8,2022,51690.40,Ativo
23,608.053.731-10,Xavier Monteiro,PF,Saúde,8,2024,76895.71,Ativo
24,72.291.759/9381-47,JuntoSeguros,PJ,Varejo,8,2019,56505.74,Ativo
25,99.193.064/9724-41,Centro Educacional Futuro,PJ,Turismo,8,2022,79298.02,Inativo
26,09.673.959/3563-40,BetaCar Motors,PJ,Varejo,8,2022,65840.11,Inativo
27,29.346.820/4466-32,DataBridge Tech,PJ,Varejo,8,2023,72775.99,Ativo
28,39.365.557/8687-57,DomésticoFácil,PJ,Construção,8,2019,59302.64,Ativo
29,663.975.721-45,Zélio Araújo,PF,Agronegócio,7,2020,41970.49,Inativo
30,132.412.415-64,Fernanda Gomes,PF,Construção,7,2022,47357.73,Ativo
31,81.667.872/6403-54,SoftEdge Sistemas,PJ,Turismo,7,2019,63084.20,Ativo
32,65.816.255/4183-04,XtraVarejo Ltda,PJ,Varejo,7,2019,53903.10,Ativo

In [14]:
# CLIENTES RADIO OURO INATIVOS (FAZER PROPOSTA DE REATIVAÇÃO)
c_radio_ouro[c_radio_ouro['status'] == 'Inativo']

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,114.433.305-90,Ana Lima,PF,Tecnologia,12,2022,72800.52,Inativo
1,25.425.824/3859-23,VidaPlena Saúde,PJ,Construção,12,2021,56918.87,Inativo
6,06.241.520/5808-29,HighClass Moda,PJ,Construção,11,2022,64822.79,Inativo
9,09.894.808/5459-80,LavouraVerde Agro,PJ,Varejo,11,2018,67934.06,Inativo
16,75.525.887/1161-98,XPrime Financeiro,PJ,Varejo,9,2018,58011.68,Inativo
25,99.193.064/9724-41,Centro Educacional Futuro,PJ,Turismo,8,2022,79298.02,Inativo
26,09.673.959/3563-40,BetaCar Motors,PJ,Varejo,8,2022,65840.11,Inativo
29,663.975.721-45,Zélio Araújo,PF,Agronegócio,7,2020,41970.49,Inativo

# ANALISE ISOLADA TV

In [15]:
df_tv

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,11.054.318/1001-25,Paço Automotivo Ltda,PJ,Varejo,5,2018,52422.44,Ativo
1,61.250.988/3939-40,LuzBrilho Beleza,PJ,Construção,8,2019,67176.18,Inativo
2,97.793.735/3814-49,InovaBuild Construtora,PJ,Turismo,6,2019,58419.93,Ativo
3,70.887.041/3756-00,InvestMax Financeiro,PJ,Automotivo,8,2023,52976.13,Ativo
4,75.525.887/1161-98,XPrime Financeiro,PJ,Varejo,6,2018,20605.06,Ativo
...,...,...,...,...,...,...,...,...
125,680.966.266-98,Bruno Souza,PF,Beleza,4,2019,43010.16,Ativo
126,498.954.683-00,Carlos Mendes,PF,Automotivo,5,2021,56284.31,Ativo
127,519.989.692-07,Diana Rocha,PF,Financeiro,9,2024,21187.49,Ativo
128,360.912.628-07,Eduardo Farias,PF,Saúde,3,2019,23879.04,Ativo
129,108.751.157-72,Fernanda Gomes,PF,Construção,3,2019,58035.71,Ativo

In [16]:
med_tv = df_tv['valor_ultima_campanha'].mean()
med_camp_tv = df_tv['qtd_campanhas'].mean()

In [17]:
c_tv_recorrente = df_tv[df_tv['qtd_campanhas'] > med_camp_tv].sort_values(by='qtd_campanhas', ascending=False)
c_tv_recorrente

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
114,93.252.144/3666-09,GrupoFit Saúde,PJ,Automotivo,12,2024,66814.29,Ativo
67,06.241.520/5808-29,HighClass Moda,PJ,Construção,12,2024,55389.93,Ativo
42,57.440.802/5303-68,InovaBuild Construtora,PJ,Automotivo,12,2022,31211.14,Inativo
28,81.599.418/5660-73,BioFarma Saúde S.A.,PJ,Construção,12,2018,38709.76,Ativo
45,14.700.177/2543-95,LuzBrilho Beleza,PJ,Varejo,12,2020,21923.92,Inativo
...,...,...,...,...,...,...,...,...
21,17.407.611/4589-21,CompreFácil Varejo,PJ,Automotivo,7,2023,54963.45,Ativo
33,653.269.484-35,Diana Rocha,PF,Financeiro,7,2020,66993.02,Ativo
101,46.807.966/1469-39,TerraFirme Construtora,PJ,Varejo,7,2021,61794.48,Ativo
66,62.328.706/8630-94,GastroTop Alimentos,PJ,Automotivo,7,2021,10723.02,Inativo
29,79.803.432/5470-41,Centro Educacional Futuro,PJ,Turismo,7,2021,69477.96,Inativo

In [19]:
c_tv_valor = df_tv[df_tv['valor_ultima_campanha'] > med_tv].sort_values(by='valor_ultima_campanha', ascending=False)
c_tv_valor

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
54,54.778.849/8140-28,UniMed Saúde,PJ,Automotivo,8,2018,79527.54,Ativo
20,77.903.143/8999-55,HotelTop Turismo,PJ,Construção,10,2024,79309.10,Ativo
88,87.228.903/1458-52,Galpão Construções,PJ,Turismo,3,2022,77204.24,Inativo
24,49.949.978/2068-08,VidaPlena Saúde,PJ,Construção,10,2019,76891.07,Inativo
78,44.730.669/9588-71,SolarTech Energia,PJ,Automotivo,11,2019,76555.95,Inativo
...,...,...,...,...,...,...,...,...
100,81.667.872/6403-54,SoftEdge Sistemas,PJ,Turismo,9,2021,39055.60,Inativo
94,02.203.325/3961-73,MegaVarejo S.A.,PJ,Automotivo,4,2018,38837.95,Ativo
28,81.599.418/5660-73,BioFarma Saúde S.A.,PJ,Construção,12,2018,38709.76,Ativo
113,72.949.970/9175-30,FrigoNorte Alimentos,PJ,Varejo,5,2022,38634.24,Ativo
48,38.029.663/6007-29,ObraFácil Construtora,PJ,Turismo,9,2023,38394.78,Ativo

In [44]:
c_tv_ouro = pd.merge(c_tv_recorrente, c_tv_valor, how="inner")
c_tv_ouro

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,93.252.144/3666-09,GrupoFit Saúde,PJ,Automotivo,12,2024,66814.29,Ativo
1,06.241.520/5808-29,HighClass Moda,PJ,Construção,12,2024,55389.93,Ativo
2,81.599.418/5660-73,BioFarma Saúde S.A.,PJ,Construção,12,2018,38709.76,Ativo
3,70.041.364/8298-92,EduMax Cursos,PJ,Automotivo,12,2021,51671.30,Ativo
4,44.730.669/9588-71,SolarTech Energia,PJ,Automotivo,11,2019,76555.95,Inativo
5,18.310.985/3045-07,ClubFit Academia,PJ,Automotivo,11,2019,43564.54,Ativo
6,52.884.461/8423-73,CompreFácil Varejo,PJ,Turismo,11,2022,55971.39,Inativo
7,43.215.405/3647-80,Haute Moda Ltda,PJ,Varejo,11,2020,45682.61,Ativo
8,88.827.020/9143-96,Haute Moda Ltda,PJ,Varejo,11,2021,48137.00,Inativo
9,45.438.966/6946-41,JetTravel Turismo,PJ,Construção,11,2022,55378.08,Inativo
10,49.949.978/2068-08,VidaPlena Saúde,PJ,Construção,10,2019,76891.07,Inativo
11,77.903.143/8999-55,HotelTop Turismo,PJ,Construção,10,2024,79309.10,Ativo
12,59.308.343/1078-01,QuantumSoft Tech,PJ,Automotivo,10,2019,42283.63,Ativo
13,90.727.027/0307-57,ZapFood Delivery,PJ,Construção,10,2023,70510.35,Ativo
14,30.743.885/8534-09,UltraFit Academia,PJ,Turismo,10,2021,51417.50,Inativo
15,13.717.564/6954-08,VitalFarm Saúde,PJ,Varejo,10,2019,54357.70,Inativo
16,76.779.132/0382-89,FuturaTech Sistemas,PJ,Construção,9,2018,57389.27,Ativo
17,13.461.344/4097-06,Drive Motors Ltda,PJ,Varejo,9,2020,44392.77,Inativo
18,81.667.872/6403-54,SoftEdge Sistemas,PJ,Turismo,9,2021,39055.60,Inativo
19,25.425.824/3859-23,VidaPlena Saúde,PJ,Construção,9,2018,44004.93,Inativo
20,37.341.091/4455-05,WebFarm Agro,PJ,Turismo,9,2022,73981.75,Ativo
21,241.592.066-54,Ana Lima,PF,Tecnologia,9,2023,43266.18,Ativo
22,027.199.816-48,Amanda Costa,PF,Alimentação,9,2022,53043.57,Inativo
23,38.029.663/6007-29,ObraFácil Construtora,PJ,Turismo,9,2023,38394.78,Ativo
24,97.025.328/6379-84,WebStore Varejo,PJ,Turismo,8,2018,74786.97,Ativo
25,608.053.731-10,Xavier Monteiro,PF,Saúde,8,2018,51091.35,Ativo
26,61.250.988/3939-40,LuzBrilho Beleza,PJ,Construção,8,2019,67176.18,Inativo
27,61.763.063/8151-55,FazendasBR Agro,PJ,Varejo,8,2020,43722.24,Inativo
28,21.753.377/2747-20,Atacadão Norte Ltda,PJ,Automotivo,8,2023,44885.62,Ativo
29,70.887.041/3756-00,InvestMax Financeiro,PJ,Automotivo,8,2023,52976.13,Ativo
30,54.778.849/8140-28,UniMed Saúde,PJ,Automotivo,8,2018,79527.54,Ativo
31,48.411.361/1768-67,LivrariaCultura,PJ,Construção,8,2020,66227.94,Ativo
32,31.699.730/9461-30,WebStore Varejo,PJ,Turismo,7,2019,52281.68,Inativo
33,17.407.611/4589-21,CompreFácil Varejo,PJ,Automotivo,7,2023,54963.45,Ativo
34,653.269.484-35,Diana Rocha,PF,Financeiro,7,2020,66993.02,Ativo
35,46.807.966/1469-39,TerraFirme Construtora,PJ,Varejo,7,2021,61794.48,Ativo
36,79.803.432/5470-41,Centro Educacional Futuro,PJ,Turismo,7,2021,69477.96,Inativo

In [45]:
c_tv_ouro[c_tv_ouro['status'] == "Inativo"]

,id_cliente,nome,tipo,segmento,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
4,44.730.669/9588-71,SolarTech Energia,PJ,Automotivo,11,2019,76555.95,Inativo
6,52.884.461/8423-73,CompreFácil Varejo,PJ,Turismo,11,2022,55971.39,Inativo
8,88.827.020/9143-96,Haute Moda Ltda,PJ,Varejo,11,2021,48137.00,Inativo
9,45.438.966/6946-41,JetTravel Turismo,PJ,Construção,11,2022,55378.08,Inativo
10,49.949.978/2068-08,VidaPlena Saúde,PJ,Construção,10,2019,76891.07,Inativo
14,30.743.885/8534-09,UltraFit Academia,PJ,Turismo,10,2021,51417.50,Inativo
15,13.717.564/6954-08,VitalFarm Saúde,PJ,Varejo,10,2019,54357.70,Inativo
17,13.461.344/4097-06,Drive Motors Ltda,PJ,Varejo,9,2020,44392.77,Inativo
18,81.667.872/6403-54,SoftEdge Sistemas,PJ,Turismo,9,2021,39055.60,Inativo
19,25.425.824/3859-23,VidaPlena Saúde,PJ,Construção,9,2018,44004.93,Inativo
22,027.199.816-48,Amanda Costa,PF,Alimentação,9,2022,53043.57,Inativo
26,61.250.988/3939-40,LuzBrilho Beleza,PJ,Construção,8,2019,67176.18,Inativo
27,61.763.063/8151-55,FazendasBR Agro,PJ,Varejo,8,2020,43722.24,Inativo
32,31.699.730/9461-30,WebStore Varejo,PJ,Turismo,7,2019,52281.68,Inativo
36,79.803.432/5470-41,Centro Educacional Futuro,PJ,Turismo,7,2021,69477.96,Inativo

In [53]:
todos = pd.merge(df_site, df_radio, how="inner", on=["id_cliente", "nome", "tipo", "segmento"], suffixes=('_site', '_radio')).merge(df_tv, how="inner", on=["id_cliente", "nome", "tipo", "segmento"], suffixes=('_site', '_tv'))
todos

,id_cliente,nome,tipo,segmento,qtd_campanhas_site,ano_ultima_interacao_site,valor_ultima_campanha_site,status_site,qtd_campanhas_radio,ano_ultima_interacao_radio,valor_ultima_campanha_radio,status_radio,qtd_campanhas,ano_ultima_interacao,valor_ultima_campanha,status
0,70.887.041/3756-00,InvestMax Financeiro,PJ,Automotivo,6,2019,39546.39,Inativo,9,2021,11451.51,Inativo,8,2023,52976.13,Ativo
1,65.939.441/4825-00,KleanHome Produtos,PJ,Automotivo,5,2023,34983.41,Ativo,3,2024,56654.60,Ativo,6,2021,22444.35,Inativo
2,91.925.646/7866-78,QualiSaúde Clínicas,PJ,Automotivo,11,2021,31186.44,Inativo,5,2021,5403.67,Ativo,12,2024,11506.52,Ativo
3,88.827.020/9143-96,Haute Moda Ltda,PJ,Varejo,2,2023,14093.72,Ativo,6,2020,14598.91,Inativo,11,2021,48137.00,Inativo
4,17.407.611/4589-21,CompreFácil Varejo,PJ,Automotivo,10,2019,57893.12,Ativo,3,2023,7776.54,Ativo,7,2023,54963.45,Ativo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,371.079.541-99,Elisa Martins,PF,Varejo,11,2021,66578.14,Ativo,4,2024,57150.54,Ativo,5,2018,56199.84,Inativo
107,114.433.305-90,Ana Lima,PF,Tecnologia,9,2019,25724.62,Inativo,12,2022,72800.52,Inativo,4,2024,35963.07,Ativo
108,680.966.266-98,Bruno Souza,PF,Beleza,4,2018,26799.25,Ativo,5,2021,52480.41,Inativo,4,2019,43010.16,Ativo
109,498.954.683-00,Carlos Mendes,PF,Automotivo,4,2019,18449.76,Ativo,1,2018,12562.69,Inativo,5,2021,56284.31,Ativo
110,519.989.692-07,Diana Rocha,PF,Financeiro,9,2019,11133.04,Inativo,3,2021,28700.25,Inativo,9,2024,21187.49,Ativo